<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loginuser extends CI_Controller{
 
    function __construct(){
        parent::__construct();      
        $this->load->model('Loginuser_model');
 
    }
 
    function index(){
        $this->load->view('Login_view_user');
    }
 
    function aksi_login(){
        $username_peminjam = $this->input->post('username_peminjam');
        $password_peminjam = $this->input->post('password_peminjam');
        $where = array(
            'username_peminjam' => $username_peminjam,
            'password_peminjam' => $password_peminjam
            );
        $cek = $this->Loginuser_model->cek_login("peminjam",$where)->num_rows();
        if($cek > 0){
 
            $data_session = array(
                'username_peminjam' => $username_peminjam,
                'status' => "login"
                );
 
            $this->session->set_userdata($data_session);
 
            redirect(base_url("barang_peminjam"));
 
        }else{
            echo "Username dan password salah !";
        }
    }
 
    function logout(){
        $this->session->sess_destroy();
        redirect(base_url('Home'));
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */